### ISSUE TITLE
Add workspace support

### ISSUE THREAD

**Issue by radomir9720** [tempo-riz/flutter-extract-to-arb-vscode#1]
Currently, if you try to export a string to ARB inside [a workspace](https://dart.dev/tools/pub/workspaces), you get the following error:
`Failed to read l10n.yaml: Error: ENOENT: no such file or directory, open '/Users/radom/StudioProjects/my_app/l10n.yaml'`

```
2025-07-04 11:30:34.934 [error] Error: ENOENT: no such file or directory, scandir '/Users/radom/StudioProjects/my_app/lib/l10n'
    at Object.readdirSync (node:fs:1585:26)
    at Object.t.readdirSync (node:electron/js2c/node_init:2:16005)
    at Er (/Users/radom/.vscode/extensions/zealousfoundry.flutter-extract-to-arb-2.4.4/dist/extension.js:48:843)
    at kr (/Users/radom/.vscode/extensions/zealousfoundry.flutter-extract-to-arb-2.4.4/dist/extension.js:48:1738)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Xb.h (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:41516)
    at Xb.h (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:41516) flutter.extractToArb undefined
```

The issue appears to be caused by a hardcoded path to the l10n.yaml file.
A potential solution would be to implement a file lookup that searches up the directory tree and uses the first found l10n.yaml file.

**Comment by tempo-riz** [comment]
hey @radomir9720 the issue is fixed in v2.5.1 feel free to reopen if not the case :)

**Comment by radomir9720** [comment]
@tempo-riz Hi. 

The error is gone, but it still doesn't work as expected. Sorry for not bringing details about the expected behaviour.

Each workspace is like a package, that has its own `pubspec.yaml`, `l10n.yaml` and localizations. So i expect the localizations to be extracted to the workspace, not to the global app.

For that, i suppose, the extension should look for a local l10n(in the workspace), and read its configurations(not the global ones).
